.travis.yml
README.md
composer.json
phpunit.xml
src/Enum.php
tests/EnumFixture.php
tests/EnumTest.php

- PSR4 compatible package
- new getKey() method (returns the key of the current value on Enum)
- new keys() method (returns the names (keys) of all constants in the Enum class)
- moved toArray() to values() method (returns all possible values as an array)
- flagged toArray() as deprecated for future removal
- new isValid() static method (check if tested value is valid on enum set)
- new isValidKey() static method (check if tested key is valid on enum set)
- new search() method (return key for searched value)

Added new methods and changed source structure to be PSR4 compatible

---

src/Enum.php

remove unnecessary use of `array_combine(array_keys($array), $array)`

some performance improvements

---

src/Enum.php
tests/EnumTest.php

Fix for search() is not type safe. Fixes #13

---

src/Enum.php

Now it doesn't need to use toArray()->array_keys->in_array, but just toArray() and isset[$key], which should be faster.

isValidKey using toArray() directly

---

README.md
src/Enum.php
tests/EnumTest.php

Add static values() method to return array of all Enum instances (fixes #18)

---

src/Enum.php

See #20 
The idea is to allow subclasses to provide a data set different from constants list. The default implementation still use constants but you can extend it to use different data source; so for instance if you have data stored in a DB you can still use your specific Enum in type hinting, but fetch data from DB.

Change calls to method toArray() from self::toArray() to static::toArray()

---

.travis.yml
README.md

#27 - Add code coverage

---

src/Enum.php
tests/EnumTest.php

Adds equals method to ease comparison between instances. Addresses #4.

Adds Enum::equals()

---

README.md
src/Enum.php
tests/EnumTest.php

Addresses suggestions from conversation in #4.
- Adds `final` to `equals()`
- Update tests per suggestions from @mirfilip
- Rewrite original tests
- Add tests proving `equals()` handles problematic values properly
- Add `equals()` to documentation

Declare equals() as final

---

.travis.yml
composer.json
tests/EnumTest.php

Allow  4.8.35, 5.7, 6.0 which all have the forward compatibility layer
So
* 4.8 will be used with old PHP version (<5.6)
* 5.7 will be used with PHP 5.6
* 6.0 will be used with PHP 7+
7.2 enabled in travis.

Use modern phpunit

---

.travis.yml
composer.json

As discussed in issue #67 this PR drops support for PHP 5.3 as preparation for the implementation of the `JsonSerializable` interface.
This change probably requires a new major release because it's a backwards incompatible change. However, this release can wait for the next PR because just now there are no new features to release.

Drop support for PHP 5.3

---

README.md

Fix #62
By recommending it directly in the README there will be no confusion whether it's intended or not.

Recommend using private constants

---

.travis.yml
src/Enum.php

This prefixed all function calls with a back space. 
This saves PHP some opcodes because it doesn't have to do the namespace lookup.
Secondly, PHP 7.2 introduced a dedicated opcode for `in_array`, but only if it is prefixed with a backspace (and the third argument is `true`). An opcode for `get_called_class` was also added to PHP 7.2.
See https://phpinternals.net/articles/optimising_internal_functions_via_new_opcode_instructions for background on the new opcodes.

Prefix all function calls with a backspace

---

src/Enum.php
tests/EnumTest.php

I found another bug:
If my enumeration contains a constant with the value "null", then the `isValidKey()` method incorrectly checks the validity:
```php
<?php
final class MyEnum extends \MyCLabs\Enum\Enum
{
public const UNDEFINED = null;
}
$valid = MyEnum::isValidKey('UNDEFINED'); // will return false because of `isset` checking
```

Fix validating key with null value

---

src/Enum.php
tests/EnumTest.php

**What?**  - New feature
**Will BC break** - No
Problem:
Lets create MyEnum
```php
<?php
final class MyEnum extends \MyCLabs\Enum\Enum
{
public const MY_VALUE = 'test-value';
}
```
Trying to create instance:
```php
<?php
$enum = new MyEnum(MyEnum::MY_VALUE); // perfectly created
``` 
And what if you create an enumeration from the same enumeration?
```php
<?php
$sameEnum = new MyEnum($enum); // will catch semantically incorrect exception
```
Thrown exception:
`Value 'test-value' is not part of MyEnum`. But 'test-value' IS part of MyEnum.
This message looks like because `__toString()` method returns property `value` in string type if it is not override
This PR add simple logic to checking argument in constructor on instance of static and not throw exception if it is.

 Create instance of enum from same enum in constructor

---

composer.json

If try use jsonserialize without enabled json extension in php you will catch an error. This PR add json to requirements. It will prevent installation if json not enabled on php

 Add ext-json to requirements for package

---

README.md

"PHP > 7.1" implies you need a version above 7.1 whereas this syntax was added as part of PHP 7.1. I've modified the text to make this clearer in the readme.

Update PHP requirement for using private keyword

---

src/Enum.php
tests/EnumTest.php

Makes "equals()" method accept anything as a parameter. It will return false if an argument is an object of different class or not an object.
One of the two PRs needed to fix https://github.com/myclabs/php-enum/issues/86

Change "equals()" method to accept anything as a parameter

---

phpunit.xml
src/PHPUnit/Comparator.php
tests/bootstrap.php

PHPUnit offers the ability to add custom comparators. In particular these offer the ability to add nice error messages:
This is a rough PR as a first draft, if you are interested in this feature please let me know and I'll polish it up.

Add a comparator to help with writing tests

---

src/Enum.php
tests/EnumTest.php
tests/InheritedEnumFixture.php

Solution for #95 
But the main principle for building architecture with enum is do not change based constants for inherited enum

 Solution for construct enum from inherited enum with incompatible value

---

.travis.yml
README.md
composer.json
psalm.xml
src/Enum.php

Let's use https://psalm.dev/ for static type checking!

Add static type checking!

---

src/Enum.php

I noticed that some of the Psalm types added in #111 could be made more precise, so I cleaned them up a bit.
I'm very interested in feedback on my decision to mark all the static methods as [`external-mutation-free`](https://psalm.dev/docs/annotating_code/supported_annotations/#psalm-external-mutation-free) rather than [`mutation-free`](https://psalm.dev/docs/annotating_code/supported_annotations/#psalm-mutation-free). It's more correct to use `external-mutation-free` as I've done, but then it's invalid to call the Enum functions in immutable contexts:
```php
EnumSubclass::ENUM_VALUE()
```
is disallowed in a function marked `psalm-immutable`, because of the internal mutation of the cache array. The mutation seems insignificant, since it could be omitted with no change to the results …

Clarify psalm types

---

src/Enum.php

This *should* be the only needed fix to stop psalm annotations from being picked up as doctrine annotations.
Note: I would like verification from someone as I did not test this with doctrine.
Closes: #113

Psalm: do not collide with doctrine templates

---

README.md

They ain't hints, they be rules.

fix legacy use of words.

---

src/Enum.php
tests/EnumTest.php

Instead of creating a new one each time, cache them.
This only matters if you're creating thousands of these objects.
I've used a small test script:
<?
require './vendor/autoload.php';
class Fast extends MyCLabs\Enum\Enum {
protected const VALUE_ONE = "one";
protected const VALUE_TWO = "two";
}
$t = microtime(true);
for ($i = 0; $i < 1000; $i++) {
Fast::VALUE_ONE();
}
$secondsPerOp = (microtime(true) - $t) / 1000;
var_dump("Microseconds per op: " . $secondsPerOp * 1000000);
Before this change, we were getting about 4us per operation,
after this, we get about 1us per op, a 4X speedup!!
Note: This only matters if you end up constructing thousands of these
objects. We end up using this library extensively and thus end up
incurring more than ten milliseconds per request just for Enum …

__callStatic: cache created Enum instances

---

src/Enum.php

When using psalm in my project with `findUnusedPsalmSuppress="true"`, I get this error:
> ERROR: UnusedPsalmSuppress - vendor/myclabs/php-enum/src/Enum.php:57:33 - This suppression is never used (see https://psalm.dev/207)
>             /** @psalm-suppress InvalidCast */

Remove unused psalm-suppress

---

src/Enum.php
tests/EnumTest.php

The current implementation of Enum requires to pass a valid enum value to class constructor. With this new named constructor we can just pass any value to enum and get an instance or unexpected value exception. In the end it's like the class constructor except for it makes psalm happy.

Added new named constructor to create enum from mixed

---

src/Enum.php
tests/EnumTest.php

Few months ago when I profile an application during some performance tests, I found that using `getKey()` was taking more CPU than expected and switching to `getValue()` for that case solved the issue; it was for logging.
For that specific case, the enum value object wasn't recreated but `getKey()` was called multiple times on the duration of a script.
In this change, the key is stored in constructor using the same cost basically.
I added to the branch the commit of @simPod from #123 as the changes there was something I also changed almost the same so he could have the credits.

Improve getKey method performance

---

.gitattributes
.travis.yml
composer.json
phpunit.xml
psalm.xml
src/Enum.php
static-analysis/EnumIsPure.php
tests/EnumTest.php

To achieve proper static analysis coverage:
* `vimeo/psalm` has been updated
* a new `static-analysis` dir has been added (to test static analysis properties **only**)
* impure `$this` usages in `Enum` have been ignored in static analysis checks
* PHP version support has been upgraded from `>=7.1` to `^7.3 || ^8.0`
* PHPUnit version has been upgraded to its latest and greatest
Fixes #134

Fix #134 by marking `Enum::__callStatic` as `@psalm-pure`

---

composer.json
src/Enum.php

suppress some psalm errors that are actually bugs in current psalm implementation or are related to deserialization workaround

suppress some psalm reported errors

---

src/Enum.php

Resolution for [Issue #144](https://github.com/myclabs/php-enum/issues/144)
As of PHP 8.1, PHP adds return type declarations to the PHP native functions ___and___ interfaces.
For the `JsonSerializable::jsonSerialize()` interface method, the new signature is:
```php
function jsonSerialize(): mixed {}
```
As this library still supports PHP 7.3, it is not possible to add this return type, as the `mixed` return type only became available in PHP 8.0.
As prior to PHP 8.0, attributes are ignored as if they were comments, it is safe to add the attribute to the library.
To prevent PHPCS tripping up over "something" existing between the function docblock and the declaration, PHPCS 3.6.0 should be used, which is the first PHPCS version with full PHP 8.0 syntax support in the sniffs; but that should …

Php8.1 resolve json serializable return datatype deprecation

---

src/Enum.php

* `@return static` is accurate enough, so it doesn't need a clarification for psalm. `static<T>` triggers false-positive alerts from static analyzers and seems to be just a mistake;
* enum entry's template type `T` is more precise as a parameter than `mixed`: it might help catch more errors when using `Enum::from`.

Fix psalm annotation on Enum::from

---

src/Enum.php

Accoring to vimeo/psalm#2571, psalm doesn't support it
A followup up to #146 (@mnapoli sorry for making you tag another version)

Remove psalm template from static method `from`

---

README.md

Document how the migration to native enums in PHP 8.1+ can be done.

document migration to native enums

---

.github/workflows/ci.yaml

**Why?**
PHP 8.1 support now [enumeration in core](https://www.php.net/enumerations). It is good for new project, but when project migrate from < 8.1 to 8.1 is possible a project use this library. This MR check compatible library with last stable PHP version.

Added PHP 8.1 to CI configuration

---

composer.json
src/Enum.php
stubs/Stringable.php

Enum class has a `__toString`, so it would be great to implements the new `Stringable` interface.
As the interface is not available for php < 8, I've ~~had the `symfony/polyfill-php-80`~~ implemented a polyfill.

Implement Stringable interface on Enum

---

.github/workflows/ci.yaml

Hi,
This PR adds PHP 8.2 to the CI versions matrix.

PHP 8.2 CI Support

---

composer.json

Fix PHPStorm warning "HTTP links are not secure"

Minor - HTTP to HTTPS for homepage link in composer.json

---

src/PHPUnit/Comparator.php

Fixes
```
PHP Deprecated:  MyCLabs\Enum\PHPUnit\Comparator::formatEnum(): Implicitly marking parameter $enum as nullable is deprecated, the explicit nullable type must be used instead in ./myclabs/php-enum/src/PHPUnit/Comparator.php on line 46
```

fix php8.4 deprecated

---

README.md

This replaces the extension for the pugx badges for version and total downloads.
The current png version is failing due to request redirection combined with [GitHub Camo](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/about-anonymized-urls) as mentioned in https://github.com/PUGX/badge-poser/issues/1195

Correct pugx badges
